IF OBJECT_ID('AIGO2.dbo.linein') IS NOT NULL DROP TABLE AIGO2.dbo.linein;
WITH V1 AS (
--尋找因系統異常而沒資料的LINEIN日期
SELECT MA.ENTER_DT,DATEADD(DAY,-7,MA.ENTER_DT) AS NEW_DT
FROM (SELECT DISTINCT CAST(ENTER_TIME AS DATE) AS ENTER_DT FROM AIGO2.dbo.orderinside) AS MA
LEFT JOIN (SELECT DISTINCT CAST(DT_GETTIME AS DATE) AS DT FROM AIGO2.dbo.linein_tp) AS J1 ON MA.ENTER_DT=J1.DT
WHERE J1.DT IS NULL
)
,V2 AS (
SELECT MA.ID_NUMBER
      ,DATEADD(DAY,7,MA.DT_GETTIME) AS DT_GETTIME
      ,DATEADD(DAY,7,MA.DT_INTIME) AS DT_INTIME_ORI
      ,CASE WHEN MA.DT_INTIME IS NULL THEN DATEADD(MINUTE,180,DATEADD(DAY,7,MA.DT_GETTIME)) ELSE DATEADD(DAY,7,MA.DT_INTIME) END AS DT_INTIME
      ,MA.NQ_PERSON
      ,MA.FG_STATUS
      ,MA.FG_FILM
      ,'ADD_DAY' AS TAG
FROM AIGO2.dbo.linein_tp AS MA
INNER JOIN V1 ON CAST(MA.DT_GETTIME AS DATE) = V1.NEW_DT
UNION
SELECT MA.ID_NUMBER
	  ,MA.DT_GETTIME
	  ,MA.DT_INTIME AS DT_INTIME_ORI
      ,CASE WHEN MA.DT_INTIME IS NULL THEN DATEADD(MINUTE,180,MA.DT_GETTIME) ELSE MA.DT_INTIME END AS DT_INTIME
      ,MA.NQ_PERSON
      ,MA.FG_STATUS
      ,MA.FG_FILM
      ,'ADJ_INTIME' AS TAG
FROM AIGO2.dbo.linein_tp AS MA
)
SELECT *
INTO AIGO2.dbo.linein
FROM V2