IF OBJECT_ID('[AIGO].[dbo].[OrderInside]') IS NOT NULL DROP TABLE [AIGO].[dbo].[OrderInside];
WITH V1 AS (
  SELECT [Serial_Number]
      ,[Order_Type]
      ,[Nation_Code]
      ,CAST([Adult_Count] AS INT) AS [Adult_Count]
      ,CAST([Kid_Count] AS INT) AS [Kid_Count]
      ,[Team_Flag]
      ,[Unhandy_Flag]
      ,[AddOrder_Times]
      ,CASE WHEN [Queue_No] = 'NULL' THEN NULL ELSE  [Queue_No] END AS [Queue_No]
      ,[Table_No]
      ,[Table_SubNo]
      ,[TakeOut_Flag]
      ,CASE WHEN [Queue_Time] = 'NULL' THEN NULL ELSE  CAST([Queue_Time] AS DATETIME) END AS [Queue_Time]
      ,CAST([Enter_Time] AS datetime) AS [Enter_Time]
      ,CAST([First_Order_Time] AS datetime) AS [First_Order_Time]
      ,CASE WHEN [First_AddOrder_Time] = 'NULL' THEN NULL ELSE  CAST([First_AddOrder_Time] AS datetime) END AS [First_AddOrder_Time]
      ,CASE WHEN [Final_AddOrder_Time] = 'NULL' THEN NULL ELSE  CAST([Final_AddOrder_Time] AS datetime) END AS [Final_AddOrder_Time]
      ,CAST([First_Dish_Time] AS datetime) AS [First_Dish_Time]
      ,CAST([Final_Dish_Time] AS datetime) AS [Final_Dish_Time]
      ,CAST([WalkOut_Time] AS datetime) AS [WalkOut_Time]
      ,CAST([Edit_Time] AS datetime) AS [Edit_Time]
      ,CASE WHEN [Nation_People] = 'NULL' THEN NULL ELSE  [Nation_People] END AS [Nation_People]
  FROM [AIGO].[dbo].[OrderInside_2016]
  UNION
  SELECT [Serial_Number]
      ,[Order_Type]
      ,[Nation_Code]
      ,CAST([Adult_Count] AS INT) AS [Adult_Count]
      ,CAST([Kid_Count] AS INT) AS [Kid_Count]
      ,[Team_Flag]
      ,[Unhandy_Flag]
      ,[AddOrder_Times]
      ,CASE WHEN [Queue_No] = 'NULL' THEN NULL ELSE  [Queue_No] END AS [Queue_No]
      ,[Table_No]
      ,[Table_SubNo]
      ,[TakeOut_Flag]
      ,CASE WHEN [Queue_Time] = 'NULL' THEN NULL ELSE  CAST([Queue_Time] AS DATETIME) END AS [Queue_Time]
      ,CAST([Enter_Time] AS datetime) AS [Enter_Time]
      ,CAST([First_Order_Time] AS datetime) AS [First_Order_Time]
      ,CASE WHEN [First_AddOrder_Time] = 'NULL' THEN NULL ELSE  CAST([First_AddOrder_Time] AS datetime) END AS [First_AddOrder_Time]
      ,CASE WHEN [Final_AddOrder_Time] = 'NULL' THEN NULL ELSE  CAST([Final_AddOrder_Time] AS datetime) END AS [Final_AddOrder_Time]
      ,CAST([First_Dish_Time] AS datetime) AS [First_Dish_Time]
      ,CAST([Final_Dish_Time] AS datetime) AS [Final_Dish_Time]
      ,CAST([WalkOut_Time] AS datetime) AS [WalkOut_Time]
      ,CAST([Edit_Time] AS datetime) AS [Edit_Time]
      ,CASE WHEN [Nation_People] = 'NULL' THEN NULL ELSE  [Nation_People] END AS [Nation_People]
  FROM [AIGO].[dbo].[OrderInside_2017]
  )
  SELECT *
  INTO [AIGO].[dbo].[OrderInside]
  FROM V1;

  